name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ develop, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare
        uses: actions/checkout@v2
      - name: Deploy_ADMIN
        uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{Secrets.HEROKU_API_KEY}}
          heroku_email: ${{Secrets.HEROKU_EMAIL}}
          heroku_app_name: ${{Secrets.HEROKU_APP_NAME_ADMIN}}
          branch: $GITHUB_REF
          dontuseforce: true
          appdir: blog-admin
          procfile: "npm start"

      - name: Deploy_USRE
        uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{Secrets.HEROKU_API_KEY}}
          heroku_email: ${{Secrets.HEROKU_EMAIL}}
          heroku_app_name: ${{Secrets.HEROKU_APP_NAME_USER}}
          branch: $GITHUB_REF
          dontuseforce: true
          appdir: blog-user
          procfile: "npm start"
