name: blog docker

on:
  push:
    branches:
      - master
      - develop

env:
  DOCKER_IMAGE: ghcr.io/yusunjo/blog-front
  VERSION: ${{ github.sha }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Create .env.development
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          RESOURCE_FILE: blog-user/.env.development
          BASE_URL: https://api-lovga.site
        run: |
          echo -e "NODE_ENV = development\nBASE_URL = $BASE_URL\nGOOGLE_API_KEY = $GOOGLE_API_KEY" > $RESOURCE_FILE
          
      - name: Login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: blog-front
          password: ${{ secrets.CR_PAT }}

      - name: docker image build and push
        run: |
          docker build -t $DOCKER_IMAGE/admin:$VERSION -f Dockerfile_admin .
          docker build -t $DOCKER_IMAGE/api:$VERSION -f Dockerfile_api .
          docker tag $DOCKER_IMAGE/admin:$VERSION $DOCKER_IMAGE/admin:latest
          docker tag $DOCKER_IMAGE/api:$VERSION $DOCKER_IMAGE/api:latest
          docker push $DOCKER_IMAGE/admin:$VERSION
          docker push $DOCKER_IMAGE/admin:latest
          docker push $DOCKER_IMAGE/api:$VERSION
          docker push $DOCKER_IMAGE/api:latest
          echo -e "${{ secrets.CR_PAT }}" > deploy/GIT-TOKEN.txt
          cat deploy/GIT-TOKEN.txt